
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

#cloudinary config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:djtnuxbw6}
cloudinary.api-key=${CLOUDINARY_API_KEY:812913212164696}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:6srczVIjFQB83mJnYtmba_jvfkQ}

spring.servlet.multipart.max-file-size=10MB

#jwt details
app.security.jwt.issuer=${JWT_ISSUER}
app.security.jwt.audience=${JWT_AUDIENCE}
app.security.jwt.secret=${JWT_SECRET:21a9ac84b028a86e39d9838de833229f563a1214c522070d3727856cdffef811}

#mail api
spring.mail.protocol=smtp
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587  
spring.mail.username=${MAIL_USERNAME:964cb2001@smtp-brevo.com}
spring.mail.password=${MAIL_PASSWORD:xsmtpsib-19b6c013e2400d1dc5e13c6ab1f5874f036d0f73d52e4e77542cc957890622c8-lccHvYlo4r22bzNX}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=mostafa.mahmoudegy10@gmail.com
spring.mail.properties.mail.debug=true