INSERT INTO category (id,category_name) VALUES
(CAST(RANDOM_UUID() AS BINARY(16)),'MEN'),
(CAST(RANDOM_UUID() AS BINARY(16)),'WOMEN'),
(CAST(RANDOM_UUID() AS BINARY(16)),'SHOES'),
(CAST(RANDOM_UUID() AS BINARY(16)),'ACCESSORIES'),
(CAST(RANDOM_UUID() AS BINARY(16)),'SPORT'),
(CAST(RANDOM_UUID() AS BINARY(16)),'BAGS');

