INSERT INTO category (id,category_name,image_url,public_id) VALUES
(CAST(RANDOM_UUID() AS BINARY(16)),'MEN','www','123'),
(CAST(RANDOM_UUID() AS BINARY(16)),'WOMEN','www','123'),
(CAST(RANDOM_UUID() AS BINARY(16)),'SHOES','www','123'),
(CAST(RANDOM_UUID() AS BINARY(16)),'ACCESSORIES','www','123'),
(CAST(RANDOM_UUID() AS BINARY(16)),'SPORT','www','123'),
(CAST(RANDOM_UUID() AS BINARY(16)),'BAGS','www','123');

